In [1]:
import numpy as np 

In [2]:
name = "aaa"
for i, b in enumerate(name):
    print(f"{i} {b}")

0 a
1 a
2 a


In [28]:

h = np.zeros((5,1))
h[1] = 1
h

array([[0.],
       [1.],
       [0.],
       [0.],
       [0.]])

In [6]:
c = np.zeros((2,2))
d = np.ones((2,2))
e = np.concatenate((c,d), axis=1)
print(str(e))

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [34]:
class Cirq_Tableau:
    
    def __init__(
        self,
        pauli_word: list[str]   
    ):

        self.column_num = len(pauli_word[0])
        self.row_num = len(pauli_word)
        
        self.ss = self.create_sign(pauli_word)
        self.xs, self.zs = self.create_tab(pauli_word)

    def create_sign(self, pauli_word: list[str]):
        temp_ss = np.zeros((self.row_num, 1))
        for pauli_string in pauli_word:
            if "-" in pauli_string:
                index = pauli_word.index(pauli_string)
                pauli_word[index] = pauli_string.replace("-", "")
                temp_ss[index] = 1
        return temp_ss
        
    def create_tab(self, pauli_word: list[str]):
        temp_x = np.zeros((self.row_num, self.column_num))
        temp_z = np.zeros((self.row_num, self.column_num))
        for i, pauli_string in enumerate(pauli_word):
            for j, pauli in enumerate(pauli_string):
                if pauli == "X" or pauli == "Y":
                    temp_x[i][j] = 1
                if pauli == "Z" or pauli == "Y":
                    temp_z[i][j] = 1
        return temp_x, temp_z
                    

    def __str__(self):
        xz = np.concatenate((self.xs, self.zs, self.ss), axis=1)
        return str(xz)

In [35]:
word = ["XX", "-ZZ"]

In [36]:
tableau = Cirq_Tableau(word)

In [37]:
print(tableau)


[[1. 1. 0. 0. 0.]
 [0. 0. 1. 1. 1.]]
